server:
  port: 8082

spring:
  application:
    name: ms-citas
  datasource:
    # Excelente el detalle de createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/db_citas?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    secret-key: "MediSoftClaveSecretaSuperSeguraYMuyLargaParaPoderFirmarLosTokensJWT"